name: 🌱 New Feature Request
description: Request adding a new feature to Processing
labels: [new feature]
body:

- type: dropdown
  id: feature-area
  attributes:
    label: Relevant sub-area for this feature?
    description: Choose the sub-area most relevant to your feature request.
    multiple: true
    options:
      - Accessibility
      - Core/Environment/Rendering
      - PDE
      - Data
      - Events
      - Image
      - IO
      - Math
      - Typography
      - Utilities
      - OpenGL
      - Contributions Manager
      - Export
      - Build process
      - Unit testing
      - Internationalization
      - Other (specify if possible)
  validations:
    required: true

- type: textarea
  id: feature-description
  attributes:
    label: Feature description
    description: Describe the feature in detail. Include how it should work and its intended impact.
  validations:
    required: true

- type: textarea
  id: benefits
  attributes:
    label: Benefits
    description: Outline how this feature would benefit users or improve Processing.
  validations:
    required: true

- type: textarea
  id: challenges
  attributes:
    label: Possible challenges
    description: Discuss any possible challenges or considerations in implementing this feature.
  validations:
    required: false

- type: textarea
  id: additional-context
  attributes:
    label: Additional context
    description: Provide any other information, links, or screenshots that could help illustrate the feature.
  validations:
    required: false

- type: dropdown
  attributes:
    label: Would you like to work on the issue?
    description: |
      Processing is an open-source, community-driven project. Let us know if you would like to help resolve this issue, or if you'd prefer it be assigned to someone else.  
      See [CONTRIBUTE.md](https://github.com/processing/processing4/blob/main/CONTRIBUTE.md) for more info about contributing.
    options:
      - Yes, I would like to work on this
      - No, please assign to someone else
      - I am not sure
  validations:
    required: true