name: 🐛 Found a Bug
description: Report broken or incorrect behavior in Processing 4. For help with your own code, please visit our forum at discourse.processing.org instead.
labels: [bug]
body:
- type: checkboxes
  id: sub-area
  attributes:
    label: Most appropriate sub-area of Processing 4?
    description: You may select more than one.
    multiple: true
    options:
        - Accessibility
        - Core/Environment/Rendering
        - Data
        - Events
        - Image
        - IO
        - Math
        - Typography
        - Utilities
        - OpenGL
        - Contributions Manager
        - Export
        - Build process
        - Unit testing
        - Internationalization
        - Other (specify if possible)
- type: input
  attributes:
    label: Processing version 
    description: Go to Help > About Processing and look in the bottom-right corner for the version number. It also appears in the title bar of every editor window.
  validations:
    required: false
- type: input
  attributes:
    label: Operating system 
    description: "Ex: Windows/MacOSX/Linux/Android/iOS along with version"
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps to reproduce this 
    description: Describe what steps will produce the bug.
    value: |
      "1.

      2.

      3."
  validations:
    required: true
- type: textarea
  attributes:
    label: snippet
    description: If applicable, include a code snippet which produces the error.
    value: |
      ```java
      // Paste your code here :)
      ```
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context about the problem here.
  validations:
    required: false
